# Codemagic CI/CD configuration file
# For more information, see https://docs.codemagic.io/yaml-basic-configuration/yaml-getting-started/

workflows:
  android-workflow:
    name: Social App Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1

    environment:
      groups:
        - google_credentials
        - cloudinary_credentials
      vars:
        CLOUDINARY_URL: "cloudinary://299232436378198:gAH-qxx0TJ1GEd_HQKKC8PsW4Rs@dduwnws1c"

    triggering:
      events:
        - push
        - pull_request
        - tag
      branch_patterns:
        - pattern: '*'
          include: true
          source: true

    scripts:
      - name: Decode google-services.json
        script: |
          echo $GOOGLE_SERVICES_JSON | base64 --decode > $CM_BUILD_DIR/app/google-services.json

      - name: Set up Cloudinary config
        script: |
          echo "Cloudinary URL: $CLOUDINARY_URL"

      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/app/local.properties"

      - name: Build Android app
        script: |
          cd app
          ./gradlew assembleRelease

      - name: Run tests
        script: |
          cd app
          ./gradlew test

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
      - app/build/outputs/**/mapping.txt
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - name@example.com
      slack:
        channel: '#builds'
        notify_on_build_start: true
